// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:rostrik_mvp/data/models/alarm_settings.dart';
import 'package:rostrik_mvp/data/models/app_alarm.dart';
import 'package:rostrik_mvp/data/models/cycle_block.dart';
import 'package:rostrik_mvp/data/models/shift.dart';
import 'package:rostrik_mvp/data/models/shift_cycle.dart';
import 'package:rostrik_mvp/data/models/shift_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmSettingsAdapter());
    registerAdapter(AppAlarmAdapter());
    registerAdapter(AppAlarmRepeatTypeAdapter());
    registerAdapter(CycleBlockAdapter());
    registerAdapter(ShiftAdapter());
    registerAdapter(ShiftCycleAdapter());
    registerAdapter(ShiftTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmSettingsAdapter());
    registerAdapter(AppAlarmAdapter());
    registerAdapter(AppAlarmRepeatTypeAdapter());
    registerAdapter(CycleBlockAdapter());
    registerAdapter(ShiftAdapter());
    registerAdapter(ShiftCycleAdapter());
    registerAdapter(ShiftTypeAdapter());
  }
}
